### ISSUE TITLE
FEATURE Option to set social networking title and images for sharing of page on Facebook and Google Plus

### ISSUE THREAD

**Issue by starlifter-nz** [hubertusanton/silverstripe-seo#13]

**Comment by mlewis-everley** [comment]
@hubertusanton Is this something you would like to add? I know we have a couple of clients requesting this feature and we could probably add a PR pretty quickly for it.

**Comment by hubertusanton** [comment]
yes, lets go for it 👍 

if you can do a PR i'll check it out

**Comment by mlewis-everley** [comment]
I have added PR #37
