### ISSUE TITLE
Evaluate Rendered Page Instead of Content

### ISSUE THREAD

**Issue by thezenmonkey** [hubertusanton/silverstripe-seo#27]
I'm wondeirng if it makes more sense to pass the page through the template parser and use that HTML for the evaluation instead of the content field. That way your SEO score would be based on $Layout

**Comment by hubertusanton** [comment]
I think thats a great idea!, that way everything is covered in the seo score, also custom page types and dataobjects. Going to create this

**Comment by hubertusanton** [comment]
this is now fixed with the latest commit and also in version 2.2.1
